### ISSUE TITLE
Debugger ideas

### ISSUE THREAD

**Issue by abcz316** [yhnu/op7t#1]
If you want to make a debugger that can be used in practice, the hardware breakpoint can only be used as an auxiliary means, not as the main means (the hardware breakpoint is used only when it is absolutely necessary, and the cost is very high, and a specific model is required). Hardware breakpoint source code, you can refer to my project. I suggest the correct idea is: hook ptrace, so that it will not be detected. Even if it is a last resort, don't be detected too fast. Wait at least half an hour. The stability of this idea is guaranteed and the workload is small. In the later stage, it can be directly connected to debuggers such as IDA. I also know the mystery of the non universal Ko driver file of each model. I can implement a Ko driver file to run in the Linux kernel of different models. At the same time, I do not recommend compiling the kernel source code directly, because many official features and functions, such as more power-saving scheduling, cannot be used.

**Comment by yhnu** [comment]
i'm a beginner of kernel develop, your rwProcMem33 help me a lot. i will do it with the ideas

**Comment by yhnu** [comment]
> If you want to make a debugger that can be used in practice, the hardware breakpoint can only be used as an auxiliary means, not as the main means (the hardware breakpoint is used only when it is absolutely necessary, and the cost is very high, and a specific model is required). Hardware breakpoint source code, you can refer to my project. I suggest the correct idea is: hook ptrace, so that it will not be detected. Even if it is a last resort, don't be detected too fast. Wait at least half an hour. The stability of this idea is guaranteed and the workload is small. In the later stage, it can be directly connected to debuggers such as IDA. I also know the mystery of the non universal Ko driver file of each model. I can implement a Ko driver file to run in the Linux kernel of different models. At the same time, I do not recommend compiling the kernel source code directly, because many official features and functions, such as more power-saving scheduling, cannot be used.

i'm a beginner of kernel develop, your rwProcMem33 help me a lot. i will do it with the ideas, can I have your contact details? my contact in my profile, please add me
