### ISSUE TITLE
arm32 App堆栈打印失败

### ISSUE THREAD

**Issue by SliverBullet5563** [yhnu/op7t#3]
大佬你好，请教一下！

我按照您的方式，https://github.com/yhnu/op7t/commit/c9af4cd3b4cfc3532f35cb44d0039ec7942893fe 加上了用户层堆栈输出，在64位App上可以正常回溯堆栈；但是在32位App上，回溯会不正常，我发现无论是32位还是64位app，都会调用到arch/arm64/kernel/stacktrace.c（32位不会调用到 arch/arm/kernel/stacktrace.c（修改成arm32堆栈回溯）），因此这里回溯的fp是arm64的fp X29。

所以想请教一下，对于arm32在arm64内核上的堆栈回溯，应该怎么改呢，或者大佬有什么思路或方向吗？感谢！（我使用的pixel 2 Android 10 内核版本 4.4.177）

**Comment by yhnu** [comment]
arm目前并没有实现，也没有对应的计划.关于fp失效，目前已解决，后期开源

**Comment by junknet** [comment]
> 
请教大佬一下 fp失效的问题解决代码 在哪里呀
