### ISSUE TITLE
URL is 404

### ISSUE THREAD

**Issue by GitChenCpp** [yhnu/op7t#4]
hello, there some url cann found,
https://github.com/yhnu/op7t/tree/dev/krhook
https://github.com/yhnu/op7t/tree/dev/kr_offline
https://github.com/yhnu/note/tree/master/kernel/01_7t_install.md

**Comment by yhnu** [comment]
fixed

**Comment by GitChenCpp** [comment]
你的邮件我已收到，届时我会查阅邮件的~感谢来信。
